services:
  gunicorn:
    profiles: ["prod"]
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: 'uv run gunicorn --bind 0.0.0.0:8000 project.wsgi'
    env_file: "secrets.env"
    volumes:
      - ..:/tracet
      - /tracet/.venv

  runserver:
    profiles: ["dev"]
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: 'uv run ./manage.py runserver 0.0.0.0:8000'
    environment:
      - DJANGO_DEBUG=true
    env_file: "secrets.env"
    ports:
      - "8123:8000"
    volumes:
      - ..:/tracet
      - /tracet/.venv

  gcnlisten:
    profiles: ["prod", "dev"]
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: 'uv run ./manage.py listengcn'
    env_file: "secrets.env"
    volumes:
      - ..:/tracet
      - /tracet/.venv

  caddy:
    profiles: ["prod"]
    image: docker.io/library/caddy:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./caddy/config:/etc/caddy
      - ./caddy/data:/data
      - ../static:/tracet/static